// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/rpc/status.proto
// Protobuf Java Version: 4.35.1

package com.google.rpc;

@com.google.protobuf.Generated
public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.rpc.Status)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getDetailsList();
  /**
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  com.google.protobuf.Any getDetails(int index);
  /**
   * <code>repeated .google.protobuf.Any details = 3;</code>
   */
  int getDetailsCount();
}
