// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/type/latlng.proto
// Protobuf Java Version: 4.35.1

package com.google.type;

@com.google.protobuf.Generated
public interface LatLngOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.type.LatLng)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double latitude = 1;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double longitude = 2;</code>
   * @return The longitude.
   */
  double getLongitude();
}
